In [1]:
import gymnasium as gym
import PendulumDLL
import numpy as np

In [2]:
env_name = "PendulumDLL-v0"
env = gym.make(env_name)
env.reset()

(array([1., 0., 0.], dtype=float32),
 {'cur_step': 0, 'theta': 0.0, 'theta_dot': 0.0})

In [3]:
vec_env = PendulumDLL.make_vec_pendulum_dll_env(num_envs=8)
obs,infos = vec_env.reset()

In [4]:
actions = np.array(4*[0.5])
print(actions)

[0.5 0.5 0.5 0.5]


In [5]:
vec_env.step(actions)

(array([[9.9999958e-01, 9.3749986e-04, 3.7500001e-02],
        [9.9999958e-01, 9.3749986e-04, 3.7500001e-02],
        [9.9999958e-01, 9.3749986e-04, 3.7500001e-02],
        [9.9999958e-01, 9.3749986e-04, 3.7500001e-02]], dtype=float32),
 array([-0.00019575, -0.00019575, -0.00019575, -0.00019575]),
 array([False, False, False, False]),
 array([False, False, False, False]),
 {'cur_step': array([1, 1, 1, 1]),
  '_cur_step': array([ True,  True,  True,  True]),
  'theta': array([0.0009375, 0.0009375, 0.0009375, 0.0009375]),
  '_theta': array([ True,  True,  True,  True]),
  'theta_dot': array([0.0375, 0.0375, 0.0375, 0.0375]),
  '_theta_dot': array([ True,  True,  True,  True])})

In [6]:
5*[4]

[4, 4, 4, 4, 4]